server:
  port: 8099

spring:
  jpa:
    properties.hibernate.hbm2ddl.auto: create-drop
  datasource:
    initialize: true
    data: classpath*:sql/init.sql

# see also http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
endpoints:
  enabled: false
  health:
    enabled: true
